name: Generate Blocklists

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - 'lists.yaml'
      - 'generate.py'

jobs:
  generate:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install requests PyYAML
      
      - name: Create lists directory
        run: mkdir -p lists
      
      - name: Generate lists
        run: python generate.py lists.yaml lists

      - name: Verify 10% drift limit
        run: python verify.py 10.0

      - name: Check for changes
        id: check_changes
        run: |
          git add lists/
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add lists/
          git commit -m "Update blocklists - $(date -u +'%Y-%m-%d %H:%M UTC')"
          git push
